/// Predefined list of Latin American, Caribbean countries and territories
/// for convocatoria eligibility. Stored as (es, en) pairs.
const List<({String es, String en})> kCountries = [
  (es: 'Argentina', en: 'Argentina'),
  (es: 'Bolivia', en: 'Bolivia'),
  (es: 'Brasil', en: 'Brazil'),
  (es: 'Chile', en: 'Chile'),
  (es: 'Colombia', en: 'Colombia'),
  (es: 'Costa Rica', en: 'Costa Rica'),
  (es: 'Cuba', en: 'Cuba'),
  (es: 'Ecuador', en: 'Ecuador'),
  (es: 'El Salvador', en: 'El Salvador'),
  (es: 'Guatemala', en: 'Guatemala'),
  (es: 'Guadalupe', en: 'Guadeloupe'),
  (es: 'Haití', en: 'Haiti'),
  (es: 'Honduras', en: 'Honduras'),
  (es: 'México', en: 'Mexico'),
  (es: 'Nicaragua', en: 'Nicaragua'),
  (es: 'Panamá', en: 'Panama'),
  (es: 'Paraguay', en: 'Paraguay'),
  (es: 'Perú', en: 'Peru'),
  (es: 'Puerto Rico', en: 'Puerto Rico'),
  (es: 'República Dominicana', en: 'Dominican Republic'),
  (es: 'Uruguay', en: 'Uruguay'),
  (es: 'Venezuela', en: 'Venezuela'),
];
